version: '3.8'

services:

  # naive-bayes-classifier-ui:
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   build:
  #     context: ../naive-bayes-classifier-ui
  #   env_file:
  #     - ../naive-bayes-classifier-ui/.env.local
  #   networks:
  #     - naive-bayes-classifier-network

  # ==============================================

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - naive-bayes-classifier-api
    ports:
      - "80:80"
    networks:
      - naive-bayes-classifier-network

  # ==============================================

  # API Spring Boot
  naive-bayes-classifier-api:
    restart: always
    ports:
      - "3002:3002"
    build:
      context: ../naive-bayes-classifier-api-spring
    networks:
      - naive-bayes-classifier-network

  # ==============================================

  # Runner NLP Node js
  naive-bayes-classifier-runner-nlp:
    restart: always
    ports:
      - "3003:3003"
    build:
      context: ../naive-bayes-classifier-runner-ts
    env_file:
      - ../naive-bayes-classifier-runner-ts/.env
    networks:
      - naive-bayes-classifier-network

  # Runner NUM Python
  naive-bayes-classifier-runner-num:
    restart: always
    ports:
      - "8000:8000"
    build:
      context: ../naive-bayes-classifier-runner-py
    env_file:
      - ../naive-bayes-classifier-runner-py/.env
    networks:
      - naive-bayes-classifier-network

  # ==============================================

  # Worker NLP Node js
  naive-bayes-classifier-worker-nlp:
    restart: always
    build:
      context: ../naive-bayes-classifier-worker-nlp
    env_file:
      - ../naive-bayes-classifier-worker-nlp/.env
    networks:
      - naive-bayes-classifier-network

  # Worker NUM Python
  naive-bayes-classifier-worker-num:
    restart: always
    build:
      context: ../naive-bayes-classifier-worker-num
    env_file:
      - ../naive-bayes-classifier-worker-num/.env
    networks:
      - naive-bayes-classifier-network
      

networks:
  naive-bayes-classifier-network:
    driver: bridge