version: '3.8'

services:

  # naive-bayes-classifier-ui:
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   build:
  #     context: ../naive-bayes-classifier-ui
  #   env_file:
  #     - ../naive-bayes-classifier-ui/.env.local
  #   networks:
  #     - naive-bayes-classifier-network


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - naive-bayes-classifier-publisher
      - naive-bayes-classifier-api
    ports:
      - "80:80"
    networks:
      - naive-bayes-classifier-network


  naive-bayes-classifier-publisher:
    restart: always
    ports:
      - "3001:3001"
    build:
      context: ../naive-bayes-classifier-publisher
    env_file:
      - ../naive-bayes-classifier-publisher/.env
    networks:
      - naive-bayes-classifier-network


  naive-bayes-classifier-api:
    restart: always
    ports:
      - "3002:3002"
    build:
      context: ../naive-bayes-classifier-api
    env_file:
      - ../naive-bayes-classifier-api/.env
    networks:
      - naive-bayes-classifier-network


  naive-bayes-classifier-runner-nlp:
    restart: always
    ports:
      - "3003:3003"
    build:
      context: ../naive-bayes-classifier-runner-ts
    env_file:
      - ../naive-bayes-classifier-runner-ts/.env
    networks:
      - naive-bayes-classifier-network


  naive-bayes-classifier-worker:
    restart: always
    build:
      context: ../naive-bayes-classifier-worker
    env_file:
      - ../naive-bayes-classifier-worker/.env
    networks:
      - naive-bayes-classifier-network


networks:
  naive-bayes-classifier-network:
    driver: bridge